name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€ 
# calm-devops8 is testing out GitHub Actions ğŸš€ 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      #ğŸ‰ The job was automatically triggered by a push event.
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      #ğŸ§ This job is now running on a Linux server hosted by GitHub!
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      #ğŸ” The name of your branch is refs/heads/master and your repository is calm-devops8/peace-tfjob.
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      #ğŸ’¡ The calm-devops8/peace-tfjob repository has been cloned to the runner.
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      #ğŸ–¥ï¸ The workflow is now ready to test your code on the runner.
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      #ğŸ This job's status is success.
      
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
      - name: Output Run SHA
        run: echo ${{ github.sha }}